/**
 * export() — Export knowledge to human-readable format.
 *
 * Formats: markdown | confluence
 *
 * Includes: active knowledge, superseded history table,
 * resolved conflicts, and stats (total nodes, avg confidence, etc).
 */

import { z } from 'zod'
import { withAuditPipeline } from '../audit/pipeline.js'
import { searchNodes } from '../graph/client.js'
import { buildAuditVersionImpact } from '../governance/provenance.js'
import { KnowledgeStatus } from '../graph/schema.js'
import { getVersionsByStatus, getVersionStatusCounts } from '../graph/queries.js'

export const schema = z.object({
  topic: z.string().optional().describe('Filter by domain (omit for all)'),
  format: z.enum(['markdown', 'confluence']).default('markdown'),
  author: z.string().optional().default('unknown'),
  session_id: z.string().optional(),
})

/**
 * @param {import('pg').Pool} pg
 * @param {z.infer<typeof schema>} input
 * @returns {Promise<Record<string, unknown>>}
 */
export async function handler(pg, input) {
  const pipelineResult = await withAuditPipeline(
    pg,
    {
      tool: 'export',
      author: input.author ?? 'unknown',
      sessionId: input.session_id,
      governanceData: { topic: input.topic, format: input.format },
    },
    async () => {
      // Query active and superseded versions from PostgreSQL
      const [activeRows, supersededRows] = await Promise.all([
        getVersionsByStatus(pg, KnowledgeStatus.ACTIVE, { topic: input.topic }),
        getVersionsByStatus(pg, KnowledgeStatus.SUPERSEDED, { topic: input.topic }),
      ])

      // Get content from Graphiti for active nodes
      const activeWithContent = await Promise.all(
        activeRows.map(async (v) => {
          let content = '[Content stored in graph — search for this key to retrieve]'
          if (v.graphiti_episode_id) {
            try {
              const searchResult = await searchNodes(`${v.topic}:${v.key}`, { limit: 1 })
              content = searchResult?.nodes?.[0]?.summary ?? content
            } catch {
              // use placeholder
            }
          }
          return { ...v, content }
        }),
      )

      // Stats
      const stats = await getVersionStatusCounts(pg, { topic: input.topic })

      const formatted = input.format === 'markdown'
        ? buildMarkdown(input.topic, activeWithContent, supersededRows, stats)
        : buildConfluence(input.topic, activeWithContent, supersededRows, stats)

      return {
        result: { format: input.format, content: formatted, stats },
        versionImpact: buildAuditVersionImpact([], []),
      }
    },
  )

  return pipelineResult.result
}

// ── Markdown format ───────────────────────────────────────────────────────────

function buildMarkdown(topic, active, superseded, stats) {
  const timestamp = new Date().toISOString()
  const topicLabel = topic ? `${topic} Domain` : 'All Domains'
  const lines = []

  lines.push(`# ${topicLabel} — Engineering Knowledge`)
  lines.push(`> Generated by Quorum | ${timestamp} | ${active.length} active nodes`)
  lines.push('')
  lines.push('## ✅ Active Knowledge')
  lines.push('')

  if (active.length === 0) {
    lines.push('_No active knowledge found._')
    lines.push('')
  }

  for (const v of active) {
    lines.push(`### ${v.key}`)
    lines.push(`**Author:** @${v.author} | **Confidence:** — | **Updated:** ${formatDate(v.created_at)}`)
    lines.push(`**Triggered by:** ${v.triggered_by}`)
    lines.push('')
    lines.push(v.content)
    lines.push('')
    lines.push('---')
    lines.push('')
  }

  lines.push('## 🔄 Superseded')
  lines.push('')
  if (superseded.length === 0) {
    lines.push('_No superseded entries._')
  } else {
    lines.push('| Key | Superseded By | Reason | Date |')
    lines.push('|-----|---------------|--------|------|')
    for (const v of superseded) {
      lines.push(
        `| ${v.key} | v${v.superseded_by_version ?? '?'} by @${v.superseded_by_author ?? '?'} | ${v.supersedes_reason ?? '—'} | ${formatDate(v.superseded_at)} |`,
      )
    }
  }
  lines.push('')

  lines.push('## 📊 Knowledge Stats')
  lines.push('')
  lines.push(`- Active nodes: ${stats[KnowledgeStatus.ACTIVE] ?? 0}`)
  lines.push(`- Draft (pending review): ${stats[KnowledgeStatus.DRAFT] ?? 0}`)
  lines.push(`- Superseded: ${stats[KnowledgeStatus.SUPERSEDED] ?? 0}`)
  lines.push(`- Deprecated: ${stats[KnowledgeStatus.DEPRECATED] ?? 0}`)
  lines.push(`- Last exported: ${timestamp}`)
  lines.push('')

  return lines.join('\n')
}

function buildConfluence(topic, active, superseded, stats) {
  // Confluence wiki markup
  const topicLabel = topic ? `${topic} Domain` : 'All Domains'
  const lines = []

  lines.push(`h1. ${topicLabel} — Engineering Knowledge`)
  lines.push(`_Generated by Quorum | ${new Date().toISOString()}_`)
  lines.push('')
  lines.push('h2. Active Knowledge')
  lines.push('')

  for (const v of active) {
    lines.push(`h3. ${v.key}`)
    lines.push(`*Author:* @${v.author} | *Updated:* ${formatDate(v.created_at)}`)
    lines.push('')
    lines.push(v.content)
    lines.push('')
    lines.push('----')
    lines.push('')
  }

  lines.push('h2. Superseded')
  lines.push('')
  if (superseded.length > 0) {
    lines.push('|| Key || Superseded By || Reason || Date ||')
    for (const v of superseded) {
      lines.push(`| ${v.key} | v${v.superseded_by_version ?? '?'} | ${v.supersedes_reason ?? '—'} | ${formatDate(v.superseded_at)} |`)
    }
  }
  lines.push('')

  return lines.join('\n')
}

function formatDate(date) {
  if (!date) return '—'
  return new Date(date).toISOString().split('T')[0]
}
